// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'replace_with_your_api_key',
    appId: '1:119839042440:web:230d1786f03090e1ed283d',
    messagingSenderId: '119839042440',
    projectId: 'shipping-control-9ce73',
    authDomain: 'shipping-control-9ce73.firebaseapp.com',
    storageBucket: 'shipping-control-9ce73.firebasestorage.app',
    measurementId: 'G-9XMXTSYT9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'replace_with_your_api_key',
    appId: '1:119839042440:android:3b5bfecc3efe416ded283d',
    messagingSenderId: '119839042440',
    projectId: 'shipping-control-9ce73',
    storageBucket: 'shipping-control-9ce73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'replace_with_your_api_key',
    appId: '1:119839042440:ios:0b573695f1a55181ed283d',
    messagingSenderId: '119839042440',
    projectId: 'shipping-control-9ce73',
    storageBucket: 'shipping-control-9ce73.firebasestorage.app',
    iosBundleId: 'com.example.shippingControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'replace_with_your_api_key',
    appId: '1:119839042440:ios:0b573695f1a55181ed283d',
    messagingSenderId: '119839042440',
    projectId: 'shipping-control-9ce73',
    storageBucket: 'shipping-control-9ce73.firebasestorage.app',
    iosBundleId: 'com.example.shippingControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'replace_with_your_api_key',
    appId: '1:119839042440:web:4c2c0e29f921c10ded283d',
    messagingSenderId: '119839042440',
    projectId: 'shipping-control-9ce73',
    authDomain: 'shipping-control-9ce73.firebaseapp.com',
    storageBucket: 'shipping-control-9ce73.firebasestorage.app',
    measurementId: 'G-8N43Y7BN0H',
  );
}
